[project]
name = "nixos-cfg"
revision = "1.0"

[providers]
age = "age://secrets.age?identity=/home/yari/.config/age/keys.txt"

[profiles.default]
ATUIN_SECRET_KEY = { description = "atuin history sync encryption key", providers = ["age"] }
ERGO_OPER_PASSWORD = { description = "ergo IRC server operator bcrypt password hash", providers = ["age"] }
USER_PASSWORD_HASH = { description = "yari login password hash (sha512-crypt)", providers = ["age"] }
